### ISSUE TITLE
Better Anticheat

### ISSUE THREAD

**Issue by DangerChamp** [donut28/an-untitled-clicker-game#10]
Currently, the anti-cheat doesn't detect autoclickers so I will be working on implementing this.

**Comment by DangerChamp** [comment]
> t work in my experience so I will be work

3.10 but sorry I wrote the issue comment wrong. I was meant to say making it better :/  I'll edit it asap. Sorry for the confussion :)

**Comment by donut28** [comment]
Thanks for your help, v1.4 includes your anti-cheat detection.
